---
abstract: 'Install the Graph::Reader modules.'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Graph-Reader
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Graph::Reader: '2.07'
  Graph::Reader::LoadClassHierarchy: 0.01
  Graph::Reader::OID: 0.02
  Graph::Reader::TGF: 0.02
  Graph::Reader::TGF::CSV: 0.01
  Graph::Reader::UnicodeTree: 0.02
  perl: 5.6.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Task-Graph-Reader
  homepage: https://github.com/tupinek/Task-Graph-Reader
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Task-Graph-Reader
version: '0.03'
